from os.path import join
include: join("rules","init.smk")

localrules: all
rule all:
    input:
        # trimmed fastqs
        expand(join(RESULTSDIR,"fastqs","{replicate}.trim.R1.fastq.gz"),replicate=REPLICATES),
        # readstats table
        join(RESULTSDIR,"fastqs","readstats.txt")

include: join("rules","preprocess.smk")