from os.path import join
include: join("rules","init.smk")

localrules: all
rule all:
    input:
        # trimmed fastqs
        expand(join(RESULTSDIR,"fastqs","{replicate}.trim.R1.fastq.gz"),replicate=REPLICATES),
        # readstats table
        join(RESULTSDIR,"fastqs","readstats.txt"),
        # cca counts as output from mimseq
        expand(join(RESULTSDIR,"{contrast}","mimseq","CCAanalysis","CCAcounts.csv"),contrast=CONTRASTS),

include: join("rules","preprocess.smk")
include: join("rules","mimseq.smk")